src/components/key-input.ts
=> ✨#31 key-input

index.html, src/main.ts, src/scripts/add-random-cell.ts, src/scripts/game-start.ts, src/scripts/key-input.ts, src/style.css
=> ✨game-start

src/main.ts, src/scripts/board.ts
=> ✨restart_btn

src/scripts/add-random-cell.ts
addrandomcell로직에서 빈셀에 2추가대신에 2또는 4추가로 변경
=> addrandomcell-2/2,4-change

src/main.ts, src/scripts/add-random-cell.ts, src/scripts/game-start.ts, src/scripts/score.ts
✨[Feature Request] current score,best score
=> 43 feature request current scorebest score

index.html, src/main.ts, src/scripts/find-move-tile.ts, src/scripts/tilemove.ts
=> ✨ #14 find-move-tile, tilemove

src/scripts/add-random-cell.ts
sane code delete in add-ramdom-cell.ts file
resolves #52
=> 🐛 same code delete in add-ramdom-cell.ts file

src/main.ts, src/scripts/marge-tiles.ts
=> ✨move TIle and merge Feature

index.html, src/main.ts, src/scripts/audio.ts, src/scripts/marge-tiles.ts, src/style.css
=> [Feature Request]all change

src/main.ts, src/scripts/find-move-tile.ts
find-move-tile.ts를 위해서 main.ts에 코드를 추가했습니다.
=> #60 add code main.ts

src/main.ts, src/scripts/find-move-tile.ts, src/scripts/tilemove.ts
---
name:  방향키 입력시 움직임 감지 
title: '[기능 요청] 원하는 기능 설명'
labels: enhancement
---
만약 방향키 입력시 이동값이 없다면
find-move-tile.ts에서 빈 객체를 반환하도록 했습니다.
main.ts에 if 문을 추가했습니다. (받는 값이 빈 객체라면 블럭 이동 x, 랜덤 블럭 생성 x)
tilemove.ts에서 사용하지 않는 코드를 비활성화 했습니다.
=> ✨ moving-check

src/main.ts, src/scripts/add-random-cell.ts, src/scripts/game-start.ts, src/scripts/marge-tiles.ts
=> 🐛[Bug] add Random sell

src/scripts/marge-tiles.ts
=> ♻️ Merge Tiles Function code reFectoring

src/scripts/marge-tiles.ts
=> ♻️ code refectoring mergetiles funtion

index.html, src/main.ts, src/scripts/modal.ts, src/style.css
=> #57 style mobile styling

src/scripts/board.ts, src/scripts/boardsize.ts, src/scripts/find-move-tile.ts, src/scripts/game-start.ts, src/scripts/marge-tiles.ts, src/style.css
Board updates and animation improvements
resolves #66
=> Board updates and animation improvements

src/scripts/find-move-tile.ts, src/scripts/game-start.ts
숫자가 병합된 후
방향키를 입력하면 병합된 숫자만 애니메이션이 적용이 안되는 문제입니다.
문제가 되는 부분을 임시로 비활성화 및, 주석으로 설명을 써 놓았습니다.
=> 🐛 aniElement deactivate-pr

src/main.ts, src/scripts/boardsize.ts
=> #20-difficulty-adjustment

index.html, src/style.css
=> #78 convert px to vw

src/scripts/game-over.ts, src/scripts/game-start.ts, src/scripts/grid-cell-verification-logic.ts, src/scripts/marge-tiles.ts, src/style.css
---
---
게임시작 버튼의 살짝의 애니메이션 효과를 주었고 mergeTiles에서 반복사용하던 cell탐색 로직을 함수화하여서 코드 리팩토링을 진행
이슈
resolves #75
=> 75 feature request create tile anime

src/main.ts, src/scripts/audio.ts, src/scripts/game-start.ts
=> audio,move anim change

index.html, src/main.ts, src/scripts/game-start.ts
=> return,mobile move

src/scripts/game-start.ts
- [] 새로운 기능 추가
- [] CSS 등 사용자 UI 디자인 변경
- [] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [] 코드 리팩토링
- [] 주석 추가 및 수정
- [] 문서 수정
- [] 테스트 추가, 테스트 리팩토링
- [] 빌드 부분 혹은 패키지 매니저 수정
- [] 파일 혹은 폴더명 수정
- [] 파일 혹은 폴더 삭제
resolves #89
=> #89 🐛 moveAniElement

src/scripts/can-move.ts, src/scripts/game-start.ts, src/style.css
46 feature request movability check
=> 46 feature request movability check

index.html, src/scripts/game-over.ts, src/scripts/game-start.ts, src/style.css
=> #45 game-over

index.html, src/main.ts, src/scripts/marge-tiles.ts, src/scripts/score.ts
=> [Bug] bug finding / dongsu

index.html, src/main.ts, src/scripts/game-start.ts, src/style.css
=> 103 bug difficulty button

index.html
=> Code Refectoring / dongsu

index.html
=> 113 bug sound img

src/main.ts, src/scripts/game-over.ts, src/scripts/game-win.ts
=> [Bug] return button

src/style.css
- [] 새로운 기능 추가
- [] CSS 등 사용자 UI 디자인 변경
- [] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [] 코드 리팩토링
- [] 주석 추가 및 수정
- [] 문서 수정
- [] 테스트 추가, 테스트 리팩토링
- [] 빌드 부분 혹은 패키지 매니저 수정
- [] 파일 혹은 폴더명 수정
- [] 파일 혹은 폴더 삭제
=> 🐛 level-modal z-index

src/main.ts
=> 103-fix-leverl-text

index.html, src/main.ts, src/scripts/game-start.ts, src/scripts/score.ts, src/style.css
=> best score

index.html, src/main.ts, src/style.css
[bug] hard mode restart/board size change
=> [bug] hard mode restart/board size change

index.html, src/main.ts, src/scripts/game-over.ts, src/scripts/game-start.ts, src/style.css
Added time attack mode and implemented related button events
resolves #106
=> ✨Added time attack mode and implemented related button events/johyunsoo

src/style.css
=> 133 bug css

index.html, src/main.ts, src/scripts/add-random-cell.ts, src/scripts/board.ts, src/scripts/can-move.ts, src/scripts/find-move-tile.ts, src/scripts/game-over.ts, src/scripts/game-start.ts, src/scripts/grid-cell-verification-logic.ts, src/scripts/marge-tiles.ts, src/scripts/score.ts, src/style.css
=> [feature] ai mode

index.html, src/main.ts, src/scripts/board.ts
=> [Bug] ai mode

src/main.ts, src/scripts/game-over.ts, src/scripts/game-start.ts
=> 138 feature request time attack mode 

src/main.ts, src/scripts/game-over.ts
fix ai board setup bug
resolves #149
=> 🐛 fix ai board setup bug

src/main.ts
=> 🐛 aistartBtn click show ai socreBoard

src/main.ts, src/scripts/audio.ts
154 bug sound bardiffficulty selection button
=> 154 bug sound bardiffficulty selection button

index.html, src/main.ts, src/style.css
=> 🐛 Update time attack UI elements and improve responsiveness

index.html, src/style.css
=> 161-fix-start-page-button

src/main.ts, src/style.css
=> 165-sound bar positon fix

src/anime/animation.css, src/main.ts, src/scripts/game-over.ts, src/style.css
=> 159 feature request hp bar

src/scripts/find-move-tile.ts
- [] 새로운 기능 추가
- [] CSS 등 사용자 UI 디자인 변경
- [] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [] 코드 리팩토링
- [] 주석 추가 및 수정
- [] 문서 수정
- [] 테스트 추가, 테스트 리팩토링
- [] 빌드 부분 혹은 패키지 매니저 수정
- [] 파일 혹은 폴더명 수정
- [] 파일 혹은 폴더 삭제
=> 🐛 find-move-tiles-build

src/main.ts, src/scripts/game-over.ts, src/style.css
=> HP Bar Animation Class Fixes and Improved Mobile Support

src/style.css
171 bug volume control slider thumb
=> 171 bug volume control slider thumb

src/main.ts
=> 🐛 fix: remove additional animation class for time attack HP on start button click and hard mode click display none level3Btn

index.html, src/scripts/game-win.ts, src/scripts/marge-tiles.ts, src/style.css
=> [BUG] AI mode,game win

src/main.ts, src/scripts/game-start.ts, src/scripts/game-win.ts, src/scripts/marge-tiles.ts, src/style.css
- [] 새로운 기능 추가
- [] CSS 등 사용자 UI 디자인 변경
- [] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [] 코드 리팩토링
- [] 문서 수정
- [] 테스트 추가, 테스트 리팩토링
- [] 빌드 부분 혹은 패키지 매니저 수정
- [] 파일 혹은 폴더명 수정
- [] 파일 혹은 폴더 삭제
=> 🐛 All-bug-teakyung
